name: CI

on: [push]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-18.04, windows-latest]
        node-version: [10.x]

    steps:
    - name: "Disable line-ending conversion"
      run: git config --global core.autocrlf false
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Install Dependencies
      run: npm install
    - name: Lint
      run: npm run lint
    - name: "List Launchers"
      run: npm run listLaunchers
    - name: Tests
      run: npm test
      timeout-minutes: 10
      env:
        HEADLESS: true
